version: "3"

services: 
    rabbitmq:
        image: rabbitmq:management
        ports:
          - "5672:5672"
          - "15672:15672"
        tty:
          true

    gateway: 
        image: bogdanvoylov/index_ms
        ports: 
            - 8080:8080
        restart: on-failure
        depends_on:
            - rabbitmq
        links: 
            - rabbitmq
                
    user:
        image: bogdanvoylov/user_ms
        restart: on-failure
        depends_on:
            - rabbitmq
        links: 
            - rabbitmq

    
          
    